[FIX] payment_worldline: show error codes in chatter
Versions
--------
- 18.0+

Steps
-----
1. Go to eCommerce;
2. add items to cart;
3. go to checkout;
4. pay with Worldline;
5. on Worldline's site, cancel transaction;
6. open order in the backend.

Issue
-----
Chatter displays:
> Error: Worldline: Received invalid transaction status CANCELLED

Cause
-----
The cancel & declined statuses aren't handled when processing
Worldline's response, leading to them being displayed as invalid.

Solution
--------
Handle the `cancel` and `declined` statuses and display the given error
code.

Also, when canceled, call `_set_canceled` instead of `_set_error`.

opw-4481602

closes odoo/odoo#196293

Signed-off-by: Levi Siuzdak <sile@odoo.com>